### ISSUE TITLE
Some definition changes or definitions or nonserials are not stable yet

### ISSUE THREAD

**Issue by xziy** [guantau/byteball-genesis#3]
i have error
`Some definition changes or definitions or nonserials are not stable yet`
, i use DAGcoin and i can start network with 4 witness (i have lucky!!! not for each case, with the same parameters), but i not can start with 7 witnesses. I'm doing everything right and I see part of the chain. (i try wailt after second "npm run genesis" 1 hour)

i use DAGCOIN

**Comment by guantau** [comment]
you can try it again as the README
